trigger:
  branches:
    include:
    - 'fb/*'
    - develop
    - release
    - master

resources:
  repositories:
  - repository: templates
    name: 'React Native Deploy Practice/Templates'
    type: git
    ref: 'main'
  - repository: self

stages:
- template: multistage_general.yml@templates
  parameters:
    variableGroupBuild: 'AppDeploy'
  