# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: macOS-latest
  
variables:
 - group: AppDeploy

steps:
- task: DownloadSecureFile@1
  name: AndroidKeystore
  displayName: 'Download Android Keystore from secure files'
  inputs:
    secureFile: 'react-native-course.jks'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    echo $(EXPO_USER)
    echo $(EXPO_PASS)

    echo "Installing libraries"
    npm install
    npm install -g expo-cli
    npm install -g turtle-cli

    echo "Login expo"
    npx expo login -u $(EXPO_USER) -p $(EXPO_PASS)
    npx expo publish --non-interactive --release-channel deployment

    echo "build android"
    expo build:android -t apk --non-interactive

    echo "Turtle setup android"
    turtle setup:android 
    EXPO_ANDROID_KEYSTORE_PASSWORD=$(ANDROID_KEYSTORE_PASSWORD) EXPO_ANDROID_KEY_PASSWORD=$(ANDROID_KEY_PASSWORD)
    
    echo "Changing to expo runner directory"
    cd /Users/runner/expo-apps/

    echo "export A=$(ls *.apk)"
    export A=$(ls *.apk)

    echo "##vso[task.setvariable variable=androidArtifact]$A"
    echo "File name to publish Android"
    echo $A

  displayName: 'npm, expo and turtle install'
